catalog/urls.py
from django.urls import path, re_path
from . import views



app_name = 'catalog'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),           
    path('index/', views.index, name='index'),     
    path('author/', views.author, name='author'),  
    path('books_list/', views.books_list, name='books_list'),  
    path('genre_list/', views.genre_list, name='genre_list'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name="book_detail"),
    re_path(r'^book/(?P<pk>\d+)$', views.BookListView.as_view(), name='books'),
    # re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('my-view', views.MyView.as_view(), name='my-view'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$',
            views.renew_book_librarian,
            name= 'renewal-book-librarian'),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('all-borrowed/', views.AllBorrowedBooksListView.as_view(), name='all-borrowed'),
]
# urlpatterns += [
#     re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
# ]


# urlpatterns += [
#     path('books/year/<int:year>/', views.books_list_year, name='books_list_year'),
#     path('books/year/<int:year>/month/<int:month>', views.books_list_month, name='books_list_month'),
#     path('books/year/<int>:year>month/<int:month/day/<int:day>/', views.views.books_list_day, name='books_list_day'),
# ]

# urlpatterns += [
#     re_path(r'^books/(?P<year>[0-9]{4})/$', views.book_list_year, name='books_list_year'),
#     re_path(r'^books/(?P<year>[0-9]{4}/)/(?P<month>0?[1-9]|1[0:2])/$', views.views.books_list_month, name='books_list_month'),
#     re_path(r'^books/(?P<year>[0-9]{4}/)/(?P<month>0?[1-9]|1[0:2])/(?P<day>0?[])/$')
# ]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views
from django.views.generic import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),      
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

catalog/models.py
# Create your models here.
from django.db import models
from django.urls import reverse
import uuid
from django.db.models import UniqueConstraint 
#Уникальность ограничения
from django.db.models.functions import Lower
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save 
 # Сигнал который отправляется после сохранения объекта в базу данных.
from django.dispatch import receiver
# Декоратор для регистрации функции-обработчика сигнала
from django.conf import settings
from datetime import date
from django.contrib.auth.models import User


# Create your models here.
@property
def is_overdue(self):
    if self.due_back and date.today() > self.due_back:
        return True
    return False


class Profile(models.Model):
    USER_ROLES=(
        ('admin','Админ'),
        ('librarian','Библиотекарь'),
        ('guest','Гость'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=USER_ROLES, default='guest')

    def __str__(self):
        return (f'{self.user.username}-{self.role}')


class Genre(models.Model):
    name = models.CharField(max_length=100, help_text="Enter a book genre")

    def __str__(self):
        return self.name

class Language(models.Model):
    
    name = models.CharField(max_length=200,
                            unique=True,
                            help_text="Enter the book's natural language")

    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message = "Language already exists (case insensitive match)"
            ),
        ]


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Перейти к описанию")
    isbn = models.CharField('ISBN', max_length=13, help_text="ISBN Entr")
    genre = models.ManyToManyField('Genre', help_text="Select a genre for this book")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), help_text="Введите UUID")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'На обслуживании'),
        ('o', 'Выдана'),
        ('a', 'Доступна'),
        ('r', 'Зарезервирована'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True,
                     default='m', help_text='book Availability')
    
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return '%s (%s)' % (self.id, self.book.title)
@property
def is_overdue(self):
    if self.due_back and date.today() > self.due_back:
        return True
    return False

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_urls(self):
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        return '%s (%s)' % (self.last_name, self.first_name)
    

catalog/forms.py
from django import forms as f
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime

class RenewBookForm(f.Form):
    renewal_date = f.DateField(
        help_text="Введите дату между сегодняшней и 4 неделями (по умолчанию 3).",
        widget=f.DateInput(attrs={'type': 'date'})
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        if data < datetime.date.today():
            raise ValidationError(_('Неверная дата - продление в прошлом'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Неверная дата - продление более чем на 4 недели'))
        
        return data

catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, BookInstance, Author, Genre
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from .forms import RenewBookForm
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin



# Create your views here.
class AllBorrowedBooksListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/all_borrowed_books.html'
    context_object_name = 'borrowed_books'
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')



class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):

    model = BookInstance
    template_name ='bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(
            borrower=self.request.user).filter(
                status__exact='o').order_by('due_back')

class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        # ваша логика для GET запроса
        return render(request, 'template_name.html')
    
    def post(self, request):
        # ваша логика для POST запроса
        pass

@login_required
def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
   
    num_books=Book.objects.all().count()

    num_instances=BookInstance.objects.all().count()
    
    # Доступные книги (статус = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    
    num_authors=Author.objects.count()

    num_genre = Genre.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    historyFive = historyFive_books(request)

    return render(
        request,'index.html',
        context={'num_books':num_books,
                 'num_instances':num_instances,
                 'num_instances_available':num_instances_available,
                 'num_authors':num_authors,
                 'num_genre':num_genre,
                 'num_visits':num_visits,
                 'historyFive_books': historyFive,}
                 )






@login_required
def author(request):
    author_list=list(Author.objects.all())
    return render(
        request, "author.html",
          context={'author_list':author_list})

# def book_search(request):
#     return render(request, "catalog/book_search", context={
#         'books':books,
#         'query':query,
#         'results_count':book_search
#     })

@login_required
def books_list(request):
    books_all = Book.objects.all()
    books_all = list(books_all)
    num_visits_book = request.session.get('num_visits_book', 0)
    request.session['num_visits_book'] = num_visits_book+1
    return render(
        request, "book_list.html",
          context={'num_visits_book':num_visits_book,
                   'books_all':books_all,
                   
                   })


class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    queryset = Book.objects.all()
    template_name = 'book_list.html'

@login_required
def genre_list(request):
    genre_all = Genre.objects.all()
    genre_all = list(genre_all)
    num_visits_genre = request.session.get('num_visits_genre', 0)
    request.session['num_visits_genre'] = num_visits_genre+1
    return render(
        request, "genre_list.html",
          context={'num_visits_genre':num_visits_genre,
                   'genre_all':genre_all,
                   
                   })

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'catalog/book_detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        book_id = self.object.pk
        recently_viewed = self.request.session.get('recently_viewed', [])
        


        book = self.get_object()
        if book:
            context['book_instances'] = BookInstance.objects.filter(book=book)
            context['available_instances'] = BookInstance.objects.filter(
                book=book, 
                status__exact='a'
            ).count()

        return context
    
    
from django.http import Http404    
@login_required
def book_detail_view(request, pk):
    try:
        book_id = Book.objects.get(pk=pk)
    except Book.DoesNotExist:
        raise Http404
    return render(
        request,
        'catalog/book_detail.html',
        context={'book':book_id,}
    )
@login_required
def book_detail(request,pk):
    book = get_object_or_404(Book,pk=pk)
    view_id = request.session.get('recently_viewed',[])
    if pk_str in view_id:
        view_id.remove(pk_str)
    view_id.insert(0,pk_str)
    request.session['recently_viewed'] = view_id[:5]
    context = {
        'book':book,
        'book_instances': BookInstance.objects.filter(book=book),
        'available_instances':BookInstance.objects.filter(book=book, status_exact='a').count(),
    }
    return render(request, 'catalog/book_detail.html', context)
        # view_id=five_view_id[:5]
        # request.session['']

@login_required
@permission_required('catalog.can_mark_returned')
def historyFive_books(request):
    viewed_ids = request.session.get('recently_viewed', [])
    books = Book.objects.filter(id__in=viewed_ids)
    book_dict = {str(book.id): book for book in books}
    ordered_books = [book_dict[book_id] for book_id in viewed_ids if book_id in book_dict]
    return ordered_books

def renew_book_librarian(request, pk):

    book_inst = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

    



# Задание 1: Среднее - История просмотренных книг
# Цель: Научиться работать со списками в сессиях.
# Задача:
# Реализуйте функционал "недавно просмотренные книги"
# При переходе на страницу детальной информации о книге добавляйте
# ее ID в список recently_viewed в сессии
# Храните только последние 5 просмотренных книг
# На главной странице или в сайдбаре показывайте список недавно
# просмотренных книг

# Задание №2. Творческое - Система закладок
# Цель: Комплексное применение сессий.
# Задача:
# ● Реализуйте систему закладок для книг (без регистрации пользователей)
# ● Пользователь может добавлять/удалять книги в "Мои закладки"
# ● На отдельной странице показывать все книги из закладок
# ● Реализовать кнопку "Очистить все закладки"


# Задание №3. Аналитическое - Время сессии
# Цель: Работа с временными метками в сессиях.
# Задача:
# Записывать время первого визита пользователя на сайт
# Показывать сколько времени пользователь провел на 
# сайте (текущее время - время первого визита)
# Сбрасывать время при новом сеансе
# (когда пользователь закрывает и открывает браузер)


# Задание 4. Ограничение частоты запросов Цель:
# Защита от злоупотреблений с помощью сессий. Задача:
# Ограничить количество запросов к форме поиска
# (не более 10 в минуту)
# Хранить в сессии время последних запросов


# Доработка домашней страницы
# 1. В главном файле шаблона (base_generic.html)
# есть блок title. Переопределите этот блок в индексном шаблоне
# (index.html) и задайте новый заголовок для этой страницы.
# 2. Модифицируйте функцию отображения таким образом,
# чтобы получать из базы данных количество жанров и количество книг,
# которые содержат в своих заголовках какое-либо слово
# (без учёта регистра), а затем передайте эти значения в шаблон.


# Форматирование данных в шаблоне
# Задача: Используйте шаблонные фильтры для форматирования вывода:
# Название библиотеки "LocalLibrary" должно отображаться
# заглавными буквами
# Числовые значения должны форматироваться с разделителями
# тысяч (например, 1,234 вместо 1234)
# Добавьте текущую дату в формате "ДД.ММ.ГГГГ"


# Новый тип книги.
# Добавь для книг языки например Lang Английский.
# Выведите авторов на главную страницу у кого сколько книг
# на разных языках
# (например:
# Стороженко Ян Романович. Английские издания: 6. Русские издания: 4.)

catalog/templates/all_borrowed_books.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>all_borrowed_books!</title>{% endblock %}
</head>
<body>
    {% block content %}
        <h1>Книги взятые для чтения!</h1>
        {% if borrowed_books %}
            <ul>
                {% for bookinst in borrowed_books %}
                    <li class ="{% if bookinst.is_overdue %} text-danger{% endif %}">
                        <a href="{% url 'book-detail' bookinst.book.pk %}">
                            {{bookinst.book.title}}
                        </a>
                        ({{bookinst.due_back}}) - 
                        <strong>Заемщик:</strong> {{ bookinst.borrower.get_full_name|default:bookinst.borrower.username }}
          {% if perms.catalog.can_mark_returned %}
            - <a href="{% url 'renew-book-librarian' bookinst.id %}">Продлить</a>
            {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Все книги в библиотеке!</p>
        {% endif %}
    {% endblock %}
</body>
</html>

catalog/templates/author.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    {% block title %}<title>Local Library</title>{% endblock %}
</head>
<body>
{% block content %}
<h1>Список авторов:</h1>

{% if author_list %}
<ul>
    {% for author in author_list %}
    <li>
        {% comment %} <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a> {% endcomment %}
        {{ author.first_name }} {{ author.last_name }} Дата рождения:{{ author.date_of_birth }}Дата смерти:{{ date_of_death }}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>В библиотеке нет книг!</p>
{% endif %}
{% endblock %}
</body>
</html>

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Local Library</title>{% endblock %}
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
</head>
<body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'catalog:index' %}">Home</a></li> 
              <li><a href="{% url 'catalog:books_list' %}">All books</a></li>  
              <li><a href="{% url 'catalog:author' %}">All authors</a></li>  
              <li><a href="{% url 'catalog:genre_list' %}">All genre</a></li>  
            </ul>
              <ul class="sidebar-nav">

            {% if user.is_authenticated %}

              <li>Пользователь: {{ user.get_username }}</li>
              <li>
                <form id="logout-form" method="POST" action="{% url 'login' %}">
                  {% csrf_token %}
                <button type="submit" class="btn btn-link">Выйти!

                </button>
                </form>
              </li>
            {% else %}
              <li><a href="{% url 'login'%}?next={{request.path}}">Войти</a></li>
            {% endif %}
            </ul>
            
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
      </div>
    </div>
    <div class="historyFive">
    {% if historyFive_books %}
      <div class="historyFive_5">
        <h3>Недавно просмотренные книги:</h3>
          <ul>
            {% for book in historyFive_books %}
              <li><a href="{% url 'book-detail' book.pk %}">{{book.title}}</a></li>
            {% endfor %}
          </ul>
      </div>
    </div>
    {% endif %}
    
</body>
</html>

catalog/templates/book_detail.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Детали:</title>{% endblock %}
</head>
<body>
    {% block content %}
    <h1>Название: {{book.title}}</h1>
    <p>Автор:{{book.author}}</p>
    <p>Количество книг у Автора:{{book.sumAuthor}}</p>
    <p>ISBN:{{book.isbn}}</p>
    <p>Перевод:{{book.language}}</p>
    <p>Жанр:{% for genre in book.genre.all %}
        {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}
    </p>
    
    <div style="margin-left:20px;margin-top:20px">
    <h4>Копия:</h4>
    {% for copy in book.bookinstance_set.all %}
        <p class="{% if copy.status == 'a' %}Статус книги:{% elif copy.status == 'd' %}
        text-danger{% else %}
        text-warning{% endif %}">
        {{ copy.get_status_display }}</p>
        <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    
    {% endfor %}
    </div>
    {% endblock %}
</body>
</html>

catalog/templates/book_list.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/book_list.css' %}" />
    <title>Document</title>
</head>
<body>
        {% block content %}
    <h1>Все книги</h1>

    {% if books_all %}
    <ul>
        {% for book in books_all %}
        <li>
            <a href="/catalog/book/{{ book.id }}/">{{ book.title }}</a> <p>Автор:{{ book.author }} Жанр:{{ book.genre }}</p>
      </li>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>В библиотеке нет книг!</p>
    {% endif %}

    <p>Вы посетили страницу "Книги" {{ num_visits_book }}{% if num_visits_book == 1 %} Time:{% else %} Times{% endif %}</p>
    {% endblock %}
</body>
</html>

catalog/templates/book_renew_librarian.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}
</body>
</html>

catalog/templates/bookinstance_list_borrowed_user.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Мои книги | Библиотека</title>{% endblock %}
</head>
<body>
    {% block content %}
    <div class="container">
        <h1>Книги в пользовании:</h1>
        {% if bookinstance_list %}
            <ul>
                {% for bookinst in bookinstance_list %}
                    <li class='{% if bookinst.is_overdue %}text-danger{% endif %}'>
                        <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">
                            {{bookinst.book.title}}</a>({{bookinst.due_back}})
                        
                    </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>Книг в пользовании не нашлось!</p>
        {% endif %}
    {% endblock %}
    </div>
</body>
</html>

catalog/templates/books.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    c
</head>
<body>
        {% comment %} {% block content %}
    <h1>Все книги</h1>

    {% if books_all %}
    <ul>
        {% for book in books_all %}
        <li>
            <strong>{{ book.title }}</strong> Автор:{{ book.author }} Жанр:{{ book.genre }}
      </li>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>В библиотеке нет книг!</p>
    {% endif %}

    <p>Вы посетили страницу "Книги" {{ num_visits_book }}{% if num_visits_book == 1 %} раз{% else %} раз{% endif %}</p>
    {% endblock %} {% endcomment %}
</body>
</html>

catalog/templates/genre_list.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/genre.css' %}" />
    {% block title %}<title>Жанры книг:</title>{% endblock %}
</head>
<body>
        {% block content %}
            <h1>Список жанров:</h1>

            {% if genre_all %}
            <ul>
                {% for genre in genre_all %}
                <li>
                    {{ genre.name }} 
                </li>
                {% endfor %}
            </ul>
            {% else %}
                <p>В библиотеке нет книг!</p>
            {% endif %}
                <p>Вы посетили страницу {{num_visits_genre}}{% if num_visits_genre == 1 %} time{% else %}times{% endif %}</p>
    {% endblock %}
</body>
</html>

catalog/templates/index.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load static %}
{% block title %}<title>Главная Индекса</title>{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  </head>
    
</head>
<body>
    {% block content %}
  <h1>Local Library Home</h1>
<p>добрпо пожаловать<em>LocalLibrary</em>, Это очень простой веб-сайт на Django, разработанный в качестве учебного примера</p>

<h2>Наполнение библиотеки! </h2>

  <p>В библиотеке зарегистрировано следующее количество записей:</p>
  <ul>
    <li><strong>Всего книг:</strong> {{ num_books }}</li>
    <li><strong>Книги с описанием:</strong> {{ num_instances }}</li>
    <li><strong>Доступные книги:</strong> {{ num_instances_available }}</li>
    <li><strong>Авторы:</strong> {{ num_authors }}</li>
    <li><strong>Жанры:</strong> {{ num_genre }}</li>
    <li><strong></li>
  </ul>
  <p>Вы посетили страницу {{num_visits}}{% if num_visits == 1 %} time{% else %}times{% endif %}</p>
{% endblock %}

{% if recently_viewed_books %}

  <h2>Вы просматривали книги:</h2>
  <ul>
    {% for book in recently_viewed_books %}
    <li><a href="{% url 'book_detail' book.pk %}">{{book.title}}</a>by:{{book.author}}</li>
    {% endfor %}
  </ul>
  {% else %}
  <p>Такой книги нету</p>
{% endif %}
</body>
</html>